#!/usr/bin/env bash
# Sync every fork listed in sources/index.json from its upstream.
# Fast-forward only — if a fork has diverged, it is reported as a failure
# and skipped (never force-push).
#
# Requires: gh CLI authenticated with a token that has `repo` scope on
# the user's forks. GitHub Actions: set FORK_SYNC_TOKEN secret and export
# it as GH_TOKEN before invocation. Locally: `gh auth login` is enough.
#
# Output:
#   - prepends a dated table to sources/sync-log.md
#   - updates sources/index.json `updated_at`

set -uo pipefail
# Note: no `set -e` — we want to keep going even when individual syncs fail.

INDEX_FILE="sources/index.json"
LOG_FILE="sources/sync-log.md"
TIMESTAMP_UTC=$(date -u +%Y-%m-%dT%H:%M:%SZ)
TIMESTAMP_DATE=$(date -u +%Y-%m-%d)
SUMMARY_TMP=$(mktemp)
trap 'rm -f "$SUMMARY_TMP"' EXIT

if ! command -v jq >/dev/null; then
  echo "::error::jq is required" >&2; exit 1
fi
if ! command -v gh >/dev/null; then
  echo "::error::gh CLI is required" >&2; exit 1
fi
if [ ! -f "$INDEX_FILE" ]; then
  echo "::error::$INDEX_FILE not found (run from repo root)" >&2; exit 1
fi

total=$(jq '.sources | length' "$INDEX_FILE")
echo "Syncing $total forks from upstream..."
echo ""

ok=0; fail=0; skipped=0

# Stream entries as TSV so the loop body runs in the main shell
# (counters survive — process substitution avoids subshell)
while IFS=$'\t' read -r fork_url upstream_url name; do
  fork_path=$(echo "$fork_url" | sed -E 's|https?://github.com/||; s|\.git$||')

  default_branch=$(gh api "repos/$fork_path" --jq '.default_branch' 2>/dev/null || echo "")
  if [ -z "$default_branch" ]; then
    printf '  %-50s  %s\n' "$name" "❌ fork not found (deleted/renamed/no access)"
    printf '| `%s` | ❌ fork not found | — |\n' "$name" >> "$SUMMARY_TMP"
    skipped=$((skipped+1))
    continue
  fi

  if result=$(gh repo sync "$fork_path" --branch "$default_branch" 2>&1); then
    printf '  %-50s  %s\n' "$name" "✅ synced ($default_branch)"
    printf '| `%s` | ✅ synced | `%s` |\n' "$name" "$default_branch" >> "$SUMMARY_TMP"
    ok=$((ok+1))
    # context-forge-source 토픽 보장 (멱등 — 이미 있어도 PUT은 OK)
    cur_topics=$(gh api "repos/$fork_path/topics" --jq '.names | join(" ")' 2>/dev/null || echo "")
    if ! echo " $cur_topics " | grep -q " context-forge-source "; then
      new_topics=$(echo "$cur_topics context-forge-source" | tr ' ' '\n' | sort -u | grep -v '^$' | jq -R . | jq -sc '{names: .}')
      gh api -X PUT "repos/$fork_path/topics" --input - >/dev/null 2>&1 <<< "$new_topics" || true
    fi
  else
    short=$(echo "$result" | tr '\n' ' ' | head -c 150)
    printf '  %-50s  %s\n' "$name" "⚠️  $short"
    printf '| `%s` | ⚠️ %s | `%s` |\n' "$name" "$short" "$default_branch" >> "$SUMMARY_TMP"
    fail=$((fail+1))
  fi
done < <(jq -r '.sources[] | "\(.fork)\t\(.upstream)\t\(.name)"' "$INDEX_FILE")

echo ""
echo "Result: ✅ $ok synced · ⚠️ $fail failed · ❌ $skipped skipped (total $total)"

# Build the dated log entry
ENTRY_FILE=$(mktemp)
{
  echo "## $TIMESTAMP_UTC"
  echo ""
  echo "**Summary**: ✅ $ok synced · ⚠️ $fail failed · ❌ $skipped skipped (total $total)"
  echo ""
  echo "| Repo | Result | Branch |"
  echo "|---|---|---|"
  cat "$SUMMARY_TMP"
  echo ""
} > "$ENTRY_FILE"

# Prepend entry under the header (newest first)
if [ -f "$LOG_FILE" ] && grep -q '^# ' "$LOG_FILE"; then
  HEADER_LINES=$(awk '/^# /{print NR; exit}' "$LOG_FILE")
  AFTER_HEADER=$((HEADER_LINES+1))
  {
    head -n "$AFTER_HEADER" "$LOG_FILE"
    echo ""
    cat "$ENTRY_FILE"
    tail -n +$((AFTER_HEADER+1)) "$LOG_FILE"
  } > "$LOG_FILE.new"
  mv "$LOG_FILE.new" "$LOG_FILE"
else
  {
    echo "# Fork Sync Log"
    echo ""
    echo "Auto-generated by \`scripts/sync-forks.sh\`. Newest entries first."
    echo ""
    cat "$ENTRY_FILE"
  } > "$LOG_FILE"
fi
rm -f "$ENTRY_FILE"

# Bump index.json updated_at
TMP_INDEX=$(mktemp)
jq --arg ts "$TIMESTAMP_DATE" '.updated_at = $ts' "$INDEX_FILE" > "$TMP_INDEX"
mv "$TMP_INDEX" "$INDEX_FILE"

# Surface failure as non-zero only if everything failed (CI signal)
if [ "$ok" -eq 0 ] && [ "$total" -gt 0 ]; then
  echo "::error::No forks synced successfully — check token scope / network" >&2
  exit 2
fi
